spring:
  profiles:
   active:
   - dev
---
spring:
  profiles: dev
  application:
   name: microconfig-config-whzl-dev
---
spring:
  profiles: default
  application:
    name: microconfig-config-whzl-test