spring:
  profiles:
   active:
   - test
---
server:
  port: 8001
# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.whzl.entity
  mapper-locations: classpath:mapper/*/*Mapper.xml

#drud数据库连接池配置
spring:
  profiles: dev
  application:
   name: microservicecloud-dept
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

eureka:
  instance:
    instance-id: microservercloud-dept8001   #指定Status中显示的服务名称   服务名称修改
    prefer-ip-address: true   #访问路径可以显示IP地址
  client:
    service-url:
      # defaultZone: http://localhost:7001/eureka/ # 单机版配置
      #集群版配置
      defaultZone: http://eureka7001.com:7001/eureka/

# 关于微服务的描述
info:
  app.name: whzl-microservicecloud
  company.name: jiangsuwuhezhilian
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001
# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.whzl.entity
  mapper-locations: classpath:mapper/*/*Mapper.xml

#drud数据库连接池配置
spring:
  profiles: test
  application:
   name: microservicecloud-dept
  datasource:
    url: jdbc:mysql://localhost:3306/cloud8003?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

eureka:
  instance:
    instance-id: microservercloud-dept8001   #指定Status中显示的服务名称   服务名称修改
    prefer-ip-address: true   #访问路径可以显示IP地址
  client:
    service-url:
      # defaultZone: http://localhost:7001/eureka/ # 单机版配置
      #集群版配置
      defaultZone: http://eureka7001.com:7001/eureka/

# 关于微服务的描述
info:
  app.name: whzl-microservicecloud
  company.name: jiangsuwuhezhilian
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}